name: Python CI - Push docker image to aws

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: chrislennon/action-aws-cli@v1.1  
        
      - name: Auth
        run: $(aws ecr get-login --no-include-email --region eu-west-1)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      
      - name: Build the Docker image
        run: docker build -t aws-test-code .

      - name: Tag the Docker Image
        run: docker tag aws-test-code:latest 538918230611.dkr.ecr.eu-west-1.amazonaws.com/aws-test-code:latest
        
      - name: Push the Docker Image
        run: docker push 538918230611.dkr.ecr.eu-west-1.amazonaws.com/aws-test-code:latest
