name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        echo "ENV ${{secrets.SECRET}}" >> Dockerfile
        docker build . --file Dockerfile --tag test-image
        
